services:
  discount-card-bot:
    container_name: discount-card-bot
    build: .
    network_mode: host
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - ADMIN_PASSWORD=your_admin_password
    volumes:
      - app-data:/app
    restart: unless-stopped

volumes:
  app-data: